### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [gy65896/SCANet#1]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

Thank you.

- Converted ONNX and self-retrained ONNX
  https://github.com/PINTO0309/PINTO_model_zoo/tree/main/375_SCANet

- test movie

  https://user-images.githubusercontent.com/33194443/233796949-dcb4a9e0-3ed2-4c7a-80ea-e51c96c80351.mp4

**Comment by gy65896** [comment]
We have added the MIT License

**Comment by PINTO0309** [comment]
Thank you!
